#!/bin/sh

: '
  Script that runs the Softmond website.

  Environment variables (default values):

  - HOST (127.0.0.1): Host used to serve the website.
  - PORT (8080): Port used to serve the website.
  - RELEASE: If not empty, build code for production environment.
'

configure_script() {
  set -e
}

configure_environment() {
  # environment variables
  if [ -z "$HOST" ]; then
    HOST="127.0.0.1"
  fi

  if [ -z "$PORT" ]; then
    PORT="8080"
  fi
}

info() {
  printf "[INFO] %s\n" "$1"
}

build_server() {
  msg="Building"
  package_name="$(< Cargo.toml grep 'name = ' | head -n 1 | cut -d'"' -f2)"
  if [ -z "$RELEASE" ]; then
    msg="$msg development"
  else
    msg="$msg production"
  fi
  msg="$msg server..."
  info "$msg"

  if [ -z "$RELEASE" ]; then
    cargo build
    target_dirname="debug"
  else
    cargo build --release
    target_dirname="release"
  fi
  TARGET_BIN="./target/$target_dirname/$package_name"
  printf "\n"
}

build_client() {
  msg="Building"
  if [ -z "$RELEASE" ]; then
    msg="$msg development"
  else
    msg="$msg production"
  fi
  msg="$msg client..."
  info "$msg"

  cd client
  if [ ! -d "node_modules" ]; then
    npm install
  fi

  RELEASE="$RELEASE" \
    ./node_modules/.bin/webpack --config webpack.config.js
  cd ..
  printf "\n"
}

build() {
  build_server
  build_client
}

run_app() {
  HOST="$HOST" PORT="$PORT" "$TARGET_BIN"
}

main() {
  configure_script
  configure_environment
  build
  run_app
}

main