name: Tests

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-server:
    name: Test server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-args:
          - ""
          - RELEASE=1
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Setup Rust
        with:
          profile: minimal
          toolchain: stable
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Update NPM
        run: npm install npm@latest -g
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.test-args }}
      - name: Build client
        run: SOURCING=1 . run && ${{ matrix.test-args }} build_client
      - name: Compile and run tests
        run: TESTS=server ${{ matrix.test-args }} ./test
  test-client:
    name: Test client
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-args:
          - ""
          - RELEASE=1
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Update NPM
        run: npm install npm@latest -g
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/client/package-lock.json') }}-${{ matrix.test-args }}
      - name: Compile and run tests
        run: TESTS=client ${{ matrix.test-args }} ./test
