name: Tests

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-server:
    name: Test server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Setup Rust
        with:
          profile: minimal
          toolchain: stable
      - run: TESTS=server ./test
